### ISSUE TITLE
Bug d'affichage : les longues descriptions de tâches ne sont pas barrées (todo)

### ISSUE THREAD

**Issue by Ilade-s** [Tifiloow/productivite-app#6]
la requête principale à école directe renvoie également les contenus de séance, or on n'en a pas besoin et cela cause un crash.

De plus, on ne renvoie pas la statut (effectué ou non) du devoir dans la BDD

**Comment by Ilade-s** [comment]
Euh du coup c'est fini mais j'ai remarqué que pour les longs textes, ils ne sont pas barrés quand faits (cf. capture jointe)
![image](https://user-images.githubusercontent.com/76600778/121056854-f0a52300-c7be-11eb-977d-2ff36cdb8f4b.png)
@BugProg  ?

**Comment by BugProg** [comment]
HI @Ilade-s !
Thank you for you report !

The cause of the problem is not the size of the tasks. You can try with : "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaA" It will works.

The problem is the name given to the ID, it was incorrect because of its syntax.

This is now fixed.

Adrien
